# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Example:

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.
s = "a"
t = "aa"

def makeDict(string):
    d = {}
    for i in string:
        if i in d:
            d[i] += 1
        else:
            d[i] = 1
    return d

d1 = makeDict(s)
d2 = makeDict(t)
for i in d2.keys():
    if i not in d1.keys():
        print(i)
        break
    else:
        if d1[i] != d2[i]:
            print(i)
            break



